// Command genstopwords reads spaCy's English stop-word list (via a sidecar
// Python script) and emits vocab/stopwords_en.go with the same data as a Go
// map literal. Run from the repo root:
//
//	go run ./internal/cmd/genstopwords
//
// Re-run whenever the upstream pin moves.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genstopwords: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	venvPy := filepath.Join(root, "testharness", ".venv", "bin", "python")
	if _, err := os.Stat(venvPy); err != nil {
		return fmt.Errorf("expected venv python at %s — run `make bootstrap-ref`", venvPy)
	}

	pyScript := `
import json, sys
from spacy.lang.en.stop_words import STOP_WORDS
json.dump(sorted(STOP_WORDS), sys.stdout, ensure_ascii=False)
`
	cmd := exec.Command(venvPy, "-c", pyScript)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("run python: %w", err)
	}

	var words []string
	if err := json.Unmarshal(out, &words); err != nil {
		return fmt.Errorf("decode python output: %w", err)
	}
	sort.Strings(words)

	target := filepath.Join(root, "vocab", "stopwords_en.go")
	var b strings.Builder
	b.WriteString("// Code generated by internal/cmd/genstopwords. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go run ./internal/cmd/genstopwords\n")
	b.WriteString("// Source: spacy.lang.en.stop_words.STOP_WORDS.\n\n")
	b.WriteString("package vocab\n\n")
	fmt.Fprintf(&b, "// enStopWords holds %d English stop words. All entries are lower-case;\n", len(words))
	b.WriteString("// callers must lowercase the lookup key (IsStopEN does so).\n")
	b.WriteString("var enStopWords = map[string]struct{}{\n")
	for _, w := range words {
		fmt.Fprintf(&b, "\t%q: {},\n", w)
	}
	b.WriteString("}\n\n")
	b.WriteString("// IsStopEN reports whether lower (a lower-cased string) is an English\n")
	b.WriteString("// stop word per spaCy's lang/en/stop_words.STOP_WORDS.\n")
	b.WriteString("func IsStopEN(lower string) bool {\n")
	b.WriteString("\t_, ok := enStopWords[lower]\n")
	b.WriteString("\treturn ok\n")
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("genstopwords: wrote %d entries to %s\n", len(words), target)
	return nil
}
