// Command genexceptions reads spaCy's English tokenizer-exceptions table
// (via a sidecar Python script) and emits lang/en/exceptions_gen.go with the
// same data as a Go map literal. Run from the repo root:
//
//	go run ./internal/cmd/genexceptions
//
// Re-run whenever the upstream pin moves.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type pyExc struct {
	Orth  string `json:"orth"`
	Norm  string `json:"norm,omitempty"`
	Lemma string `json:"lemma,omitempty"`
	POS   string `json:"pos,omitempty"`
	Tag   string `json:"tag,omitempty"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genexceptions: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	venvPy := filepath.Join(root, "testharness", ".venv", "bin", "python")
	if _, err := os.Stat(venvPy); err != nil {
		return fmt.Errorf("expected venv python at %s — run `make bootstrap-ref`", venvPy)
	}

	// NOTE: a survey of spacy.lang.en.tokenizer_exceptions shows the only
	// real per-piece attribute keys are ORTH (65) and NORM (67). The
	// LEMMA/POS/TAG fields are kept in the generated literal for
	// compatibility with the SpecialPiece struct (they emit as ""), but no
	// upstream entry sets them. A non-attr "number" key (singular/plural
	// marker for some auxiliary clitics) is ignored — it is not a token
	// attribute and does not affect tokenization.
	pyScript := `
import json, sys
from spacy.lang.en.tokenizer_exceptions import TOKENIZER_EXCEPTIONS
from spacy.attrs import ORTH, NORM, LEMMA, POS, TAG
out = {}
for k, pieces in TOKENIZER_EXCEPTIONS.items():
    out[k] = [
        {"orth": p.get(ORTH, ""), "norm": p.get(NORM, ""),
         "lemma": p.get(LEMMA, ""),
         "pos": p.get(POS, ""), "tag": p.get(TAG, "")}
        for p in pieces
    ]
json.dump(out, sys.stdout, ensure_ascii=False)
`
	cmd := exec.Command(venvPy, "-c", pyScript)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("run python: %w", err)
	}

	var table map[string][]pyExc
	if err := json.Unmarshal(out, &table); err != nil {
		return fmt.Errorf("decode python output: %w", err)
	}

	keys := make([]string, 0, len(table))
	for k := range table {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	target := filepath.Join(root, "lang", "en", "exceptions_gen.go")
	var b strings.Builder
	b.WriteString("// Code generated by internal/cmd/genexceptions. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go run ./internal/cmd/genexceptions\n")
	b.WriteString("// Source: spacy.lang.en.tokenizer_exceptions @ upstream commit 0069cf99b6.\n\n")
	b.WriteString("package en\n\n")
	b.WriteString("import \"github.com/bioshock/gospacy/v3/tokenizer\"\n\n")
	fmt.Fprintf(&b, "// GeneratedExceptions holds %d English exception entries.\n", len(keys))
	b.WriteString("var GeneratedExceptions = map[string][]tokenizer.SpecialPiece{\n")
	for _, k := range keys {
		pieces := table[k]
		fmt.Fprintf(&b, "\t%s: {", goQuote(k))
		for i, p := range pieces {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "{Orth: %s, Norm: %s, Lemma: %s, POS: %s, Tag: %s}",
				goQuote(p.Orth), goQuote(p.Norm), goQuote(p.Lemma), goQuote(p.POS), goQuote(p.Tag))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("genexceptions: wrote %d entries to %s\n", len(keys), target)
	return nil
}

func goQuote(s string) string {
	return fmt.Sprintf("%q", s)
}
